/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as ChallengeRouteImport } from './routes/challenge'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RegisterSplatRouteImport } from './routes/register.$'
import { Route as LoginSplatRouteImport } from './routes/login.$'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengeRoute = ChallengeRouteImport.update({
  id: '/challenge',
  path: '/challenge',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterSplatRoute = RegisterSplatRouteImport.update({
  id: '/register/$',
  path: '/register/$',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginSplatRoute = LoginSplatRouteImport.update({
  id: '/login/$',
  path: '/login/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/challenge': typeof ChallengeRoute
  '/history': typeof HistoryRoute
  '/settings': typeof SettingsRoute
  '/login/$': typeof LoginSplatRoute
  '/register/$': typeof RegisterSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/challenge': typeof ChallengeRoute
  '/history': typeof HistoryRoute
  '/settings': typeof SettingsRoute
  '/login/$': typeof LoginSplatRoute
  '/register/$': typeof RegisterSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/challenge': typeof ChallengeRoute
  '/history': typeof HistoryRoute
  '/settings': typeof SettingsRoute
  '/login/$': typeof LoginSplatRoute
  '/register/$': typeof RegisterSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/challenge'
    | '/history'
    | '/settings'
    | '/login/$'
    | '/register/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/challenge' | '/history' | '/settings' | '/login/$' | '/register/$'
  id:
    | '__root__'
    | '/'
    | '/challenge'
    | '/history'
    | '/settings'
    | '/login/$'
    | '/register/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChallengeRoute: typeof ChallengeRoute
  HistoryRoute: typeof HistoryRoute
  SettingsRoute: typeof SettingsRoute
  LoginSplatRoute: typeof LoginSplatRoute
  RegisterSplatRoute: typeof RegisterSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenge': {
      id: '/challenge'
      path: '/challenge'
      fullPath: '/challenge'
      preLoaderRoute: typeof ChallengeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/$': {
      id: '/register/$'
      path: '/register/$'
      fullPath: '/register/$'
      preLoaderRoute: typeof RegisterSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/$': {
      id: '/login/$'
      path: '/login/$'
      fullPath: '/login/$'
      preLoaderRoute: typeof LoginSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChallengeRoute: ChallengeRoute,
  HistoryRoute: HistoryRoute,
  SettingsRoute: SettingsRoute,
  LoginSplatRoute: LoginSplatRoute,
  RegisterSplatRoute: RegisterSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
